// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Lockdown.AcceptanceTests.Roles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Get a list of roles")]
    public partial class GetAListOfRolesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Get a list of roles.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Get a list of roles", "As a policy administrator\r\nI can get a list of roles\r\nso that I can see the roles" +
                    " I can apply", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Two Roles")]
        public virtual void TwoRoles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two Roles", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have an azman store");
#line 8
 testRunner.And("the store has an application called MyApp");
#line 9
 testRunner.And("the store has an role called role1");
#line 10
 testRunner.And("the store has an role called role2");
#line 11
 testRunner.When("I open the store");
#line 12
 testRunner.And("I get the list of roles");
#line 13
 testRunner.Then("I get a list of roles with 2 item(s) in it");
#line 14
 testRunner.And("I get a list with a role called role1 in it");
#line 15
 testRunner.And("I get a list with a role called role2 in it");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No Roles")]
        public virtual void NoRoles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No Roles", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I have an azman store");
#line 19
 testRunner.And("the store has an application called MyApp");
#line 20
 testRunner.And("the store has no tasks");
#line 21
 testRunner.When("I open the store");
#line 22
 testRunner.And("I get the list of roles");
#line 23
 testRunner.Then("I get an empty list of roles");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Two Roles and one task")]
        public virtual void TwoRolesAndOneTask()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two Roles and one task", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
 testRunner.Given("I have an azman store");
#line 27
 testRunner.And("the store has an application called MyApp");
#line 28
 testRunner.And("the store has an task called task1");
#line 29
 testRunner.And("the store has an role called role1");
#line 30
 testRunner.And("the store has an role called role2");
#line 31
 testRunner.When("I open the store");
#line 32
 testRunner.And("I get the list of roles");
#line 33
 testRunner.Then("I get a list of roles with 2 item(s) in it");
#line 34
 testRunner.And("I get a list with a role called role1 in it");
#line 35
 testRunner.And("I get a list with a role called role2 in it");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Role contains two operations")]
        public virtual void RoleContainsTwoOperations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Role contains two operations", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("I have an azman store");
#line 39
 testRunner.And("the store has an application called MyApp");
#line 40
 testRunner.And("the store has an role called role1");
#line 41
 testRunner.And("the store has an operation X with id 1");
#line 42
 testRunner.And("the store has an operation Y with id 2");
#line 43
 testRunner.And("the role role1 contains operation 1");
#line 44
 testRunner.And("the role role1 contains operation 2");
#line 45
 testRunner.When("I open the store");
#line 46
 testRunner.And("I get the list of roles");
#line 47
 testRunner.Then("I get a list of roles with 1 item(s) in it");
#line 48
 testRunner.And("the role contains operation 1");
#line 49
 testRunner.And("the role contains operation 2");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Role contains two tasks")]
        public virtual void RoleContainsTwoTasks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Role contains two tasks", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.Given("I have an azman store");
#line 53
 testRunner.And("the store has an application called MyApp");
#line 54
 testRunner.And("the store has an role called role1");
#line 55
 testRunner.And("the store has an task called task1");
#line 56
 testRunner.And("the store has an task called task2");
#line 57
 testRunner.And("the role role1 contains task task1");
#line 58
 testRunner.And("the role role1 contains task task2");
#line 59
 testRunner.When("I open the store");
#line 60
 testRunner.And("I get the list of roles");
#line 61
 testRunner.Then("I get a list of roles with 1 item(s) in it");
#line 62
 testRunner.And("the role should contain 2 tasks");
#line 63
 testRunner.And("the role contains task task1");
#line 64
 testRunner.And("the role contains task task2");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
